version: '3.8'

services:
  backend:
    image: banaszakigor/tic-tac-toe-cloud-backend:latest
    environment:
      - API_DOMAIN=${API_DOMAIN}
    ports:
      - 8080:8080

  frontend:
    image: banaszakigor/tic-tac-toe-cloud-frontend:latest
    environment:
      - REACT_APP_API_DOMAIN=${API_DOMAIN}
    ports:
      - 3000:3000

    depends_on:
      - backend
